name: SSE CI/CD

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install spell check
        run: pip install black
      - name: Run spell check
        run: black --check .

  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: pip install pytest coverage numpy matplotlib
      - name: Run coverage
        run: coverage run -m pytest .
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-db
          path: .coverage
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  coverage_report:
    runs-on: ubuntu-24.04

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install coverage dependencies
        run: pip install coverage
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-db
      - name: Generate coverage report
        run: coverage report -m
      - name: Generate coverage XML report
        run: coverage xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error
          retention-days: 14