  name: SSE CI Workflow

  on:
    push:
      branches:
        - main

  jobs:
    style_check:
      name: Style Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - name: Install Dependencies
          run: |
            pip install black

        - name: Run Black
          run: black --check .

    test:
      name: Run Tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - name: Install Dependencies
          run: |
            pip install pytest coverage numpy matplotlib

        - name: Run Tests
          run: |
            coverage run -m pytest .

        - name: Upload Coverage
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage
            path: .coverage
            retention-days: 1
            include-hidden-files: true

    coverage_report:
      name: Coverage Report
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - name: Install Coverage
          run: |
            pip install coverage

        - name: Download coverage
          uses: actions/download-artifact@v4
          with:
            name: code-coverage

        - name: Generate Coverage Report
          run: |
            coverage report -m
            coverage xml

        - name: Upload Coverage XML
          uses: actions/upload-artifact@v4
          with:
            name: coverage-xml
            path: coverage.xml
            retention-days: 14
