name: SSE CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black --check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage numpy matplotlib

      - name: Run Tests
        run: |
          coverage run -m pytest .

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: artifact.coverage
          retention-days: 1
          include-hidden-files: true

  coverage_report:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Generate Coverage Report
        run: |
          coverage report
          coverage xml

      - name: Upload Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14
